config/routes.rb
Gypsy::Application.routes.draw do
  get "logic_gypsy/index"

  get "logic_gypsy/show"

  resources :blr_places

  resources :places
  match '/home' => 'logic_gypsy#index' , :as => :home
  match '/show'  => 'logic_gypsy#show' , :as => :show

  match 'auth/:provider/callback', to: 'sessions#create'
match 'auth/failure', to: redirect('/')
match 'signout', to: 'sessions#destroy', as: 'signout'  
match 'application/application' ,to: 'application#application', as: 'application'

end

app/models/blr_place.rb
class BlrPlace < ActiveRecord::Base
  attr_accessible :place_name, :tags
end

app/models/place.rb
class Place < ActiveRecord::Base
  attr_accessible :place_name, :tags
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :location, :name, :oauth_expires_at, :oauth_token, :provider, :string, :uid

  	def self.from_omniauth(auth)
  where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
    user.provider = auth.provider
    user.uid = auth.uid
    user.name = auth.info.name
    user.location = auth.extra.raw_info.location.name
    user.oauth_token = auth.credentials.token
    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
    user.save!
  end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  private
def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
helper_method :current_user

end

app/controllers/blr_places_controller.rb
class BlrPlacesController < ApplicationController
  # GET /blr_places
  # GET /blr_places.json
  def index
    @blr_places = BlrPlace.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blr_places }
    end
  end

  # GET /blr_places/1
  # GET /blr_places/1.json
  def show
    @blr_place = BlrPlace.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blr_place }
    end
  end

  # GET /blr_places/new
  # GET /blr_places/new.json
  def new
    @blr_place = BlrPlace.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blr_place }
    end
  end

  # GET /blr_places/1/edit
  def edit
    @blr_place = BlrPlace.find(params[:id])
  end

  # POST /blr_places
  # POST /blr_places.json
  def create
    @blr_place = BlrPlace.new(params[:blr_place])

    respond_to do |format|
      if @blr_place.save
        format.html { redirect_to @blr_place, notice: 'Blr place was successfully created.' }
        format.json { render json: @blr_place, status: :created, location: @blr_place }
      else
        format.html { render action: "new" }
        format.json { render json: @blr_place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blr_places/1
  # PUT /blr_places/1.json
  def update
    @blr_place = BlrPlace.find(params[:id])

    respond_to do |format|
      if @blr_place.update_attributes(params[:blr_place])
        format.html { redirect_to @blr_place, notice: 'Blr place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blr_place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blr_places/1
  # DELETE /blr_places/1.json
  def destroy
    @blr_place = BlrPlace.find(params[:id])
    @blr_place.destroy

    respond_to do |format|
      format.html { redirect_to blr_places_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/logic_gypsy_controller.rb
class LogicGypsyController < ApplicationController
  def index
  end
   
  def show
     age=params[:txt_age]
    # intreasts=params[:txt_inter]
     destination=params[:txt_from]
     t=Place.where("place_name like '#{destination}'")
     places=""
     answer=""
     puts "t= #{t}"
     answer=t.first[:tags]
     @results=[]
     answer.split(",").each do |intreasts|
       @results << BlrPlace.where("tags like '%#{intreasts}%'")
     end
  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  # GET /places
  # GET /places.json
  def index
    @places = Place.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @places }
    end
  end

  # GET /places/1
  # GET /places/1.json
  def show
    @place = Place.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @place }
    end
  end

  # GET /places/new
  # GET /places/new.json
  def new
    @place = Place.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @place }
    end
  end

  # GET /places/1/edit
  def edit
    @place = Place.find(params[:id])
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(params[:place])

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render json: @place, status: :created, location: @place }
      else
        format.html { render action: "new" }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /places/1
  # PUT /places/1.json
  def update
    @place = Place.find(params[:id])

    respond_to do |format|
      if @place.update_attributes(params[:place])
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place = Place.find(params[:id])
    @place.destroy

    respond_to do |format|
      format.html { redirect_to places_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blr_places_helper.rb
module BlrPlacesHelper
end

app/helpers/logic_gypsy_helper.rb
module LogicGypsyHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/blr_places/_form.html.erb
<%= form_for(@blr_place) do |f| %>
  <% if @blr_place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blr_place.errors.count, "error") %> prohibited this blr_place from being saved:</h2>

      <ul>
      <% @blr_place.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :place_name %><br />
    <%= f.text_field :place_name %>
  </div>
  <div class="field">
    <%= f.label :tags %><br />
    <%= f.text_field :tags %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blr_places/edit.html.erb
<h1>Editing blr_place</h1>

<%= render 'form' %>

<%= link_to 'Show', @blr_place %> |
<%= link_to 'Back', blr_places_path %>

app/views/blr_places/index.html.erb
<h1>Listing blr_places</h1>

<table>
  <tr>
    <th>Place name</th>
    <th>Tags</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @blr_places.each do |blr_place| %>
  <tr>
    <td><%= blr_place.place_name %></td>
    <td><%= blr_place.tags %></td>
    <td><%= link_to 'Show', blr_place %></td>
    <td><%= link_to 'Edit', edit_blr_place_path(blr_place) %></td>
    <td><%= link_to 'Destroy', blr_place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Blr place', new_blr_place_path %>

app/views/blr_places/new.html.erb
<h1>New blr_place</h1>

<%= render 'form' %>

<%= link_to 'Back', blr_places_path %>

app/views/blr_places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Place name:</b>
  <%= @blr_place.place_name %>
</p>

<p>
  <b>Tags:</b>
  <%= @blr_place.tags %>
</p>


<%= link_to 'Edit', edit_blr_place_path(@blr_place) %> |
<%= link_to 'Back', blr_places_path %>

app/views/layouts/application.html.erb
<div id="user_nav">
  <% if current_user %>
    Signed in as <strong><%= current_user.name %></strong>!
    <%= link_to "Sign out", signout_path, id: "sign_out" %>
  <% else %>
    <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
  <% end %>
</div>	

app/views/logic_gypsy/index.html.erb
<h1>Welcome</h1>
<%= form_tag('/show', :method=>'post', :multipart => true) do %>
From: <%= text_field_tag "txt_from"%> </br>
Age: <%= text_field_tag "txt_age"%> </br>
<%= submit_tag 'find' %>
<% end %>

app/views/logic_gypsy/show.html.erb
<h1>Results</h1>
suggestions : <% @results.each do |r| %>
	           <% r.each do |rr|  %>
	           <%= rr.place_name %>
	           <% end %>
	           <% end %>

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :place_name %><br />
    <%= f.text_field :place_name %>
  </div>
  <div class="field">
    <%= f.label :tags %><br />
    <%= f.text_field :tags %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<h1>Listing places</h1>

<table>
  <tr>
    <th>Place name</th>
    <th>Tags</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @places.each do |place| %>
  <tr>
    <td><%= place.place_name %></td>
    <td><%= place.tags %></td>
    <td><%= link_to 'Show', place %></td>
    <td><%= link_to 'Edit', edit_place_path(place) %></td>
    <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<h1>New place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Place name:</b>
  <%= @place.place_name %>
</p>

<p>
  <b>Tags:</b>
  <%= @place.tags %>
</p>


<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>